name: 'wformat setup'
description: 'Prepare environment: checkout, node/python/ninja, cmake build'
runs:
  using: 'composite'
  steps:
    - name: Set up Node.js (root package.json)
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Ensure CMake and Ninja are installed
      uses: lukka/get-cmake@latest

    - name: CMake Configure
      shell: bash
      run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE:STRING=Debug

    - name: CMake Build (ALL)
      shell: bash
      run: cmake --build build --parallel --config Debug --target python_project_setup
