name: 'wformat setup'
description: 'Prepare environment: checkout, node/python/ninja, cmake build'
runs:
  using: 'composite'
  steps:
    - name: Set up Node.js (root package.json)
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Ensure CMake and Ninja are installed
      uses: lukka/get-cmake@latest

    - name: Add msbuild to PATH
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v2

    - name: CMake Configure (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: cmake -S . -B build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE:STRING=Debug

    - name: CMake Configure (non Windows)
      if: runner.os != 'Windows'
      shell: bash
      run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE:STRING=Debug
