name: Build Visual Studio Extension

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Override version (e.g. 1.2.3)."
        required: true

permissions:
  contents: read

env:
  NODE_VERSION: "20"
  EXT_BASE: wformat
  VSIX_FILE: WFormatVSIX.vsix

jobs:
  build-binaries:
    name: Build Binary (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2025
            tag: win-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment (composite action)
        uses: ./.github/actions/setup-action
        
      - name: Prep version (install tooling & set version)
        run: |
          python -m pip install --upgrade pip toml
          python scripts/set_version.py "${{ github.event.inputs.version }}"
          echo "Version set to ${{ github.event.inputs.version }}"

      - name: CMake Build (ALL)
        shell: bash
        run: cmake --build build --parallel --config Debug --target pyinstaller_bundle_for_vs

      - name: Rename platform folder (append platform tag)
        shell: bash
        run: |
          mkdir -p extensions/vs/dist/${{ matrix.tag }}
          mv extensions/vs/dist/$EXT_BASE extensions/vs/dist/${{ matrix.tag }}/$EXT_BASE

      - name: Build VSIX
        shell: pwsh
        run: ./scripts/build-vsix.ps1 -Version ${{ github.event.inputs.version }}

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vs-vsix@${{ github.event.inputs.version }}
          path: ${{ env.VSIX_FILE }}
          if-no-files-found: error
