name: Run Tests

on:
  workflow_dispatch:
  
jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-action

      - name: CMake Build
        shell: bash
        run: cmake --build build --parallel --config Debug --target python_project_setup

      - name: Install dependencies
        run: pip install -e .[test]

      - name: Run tests
        run: pytest -q
